Fixed striked normal price was displayed for variable products regardless of backend setting.
netzstrategen/wordpress-shop-standards pull request #116
Opened 2020-08-27 09:18 UTC by juanlopez4691

### Ticket
- [_shop-standards_show_sale_price_only broken on product detail pages & related products](https://app.asana.com/0/30156186242982/1190933470177681/f)

### Description
-

2020-08-27 12:53 UTC, LucaPipolo requested changes

2020-08-27 12:53 UTC, LucaPipolo commented on src/WooCommerce.php
> +      // $price = apply_filters($current_filter, $price, $product);
⚠️

2020-08-27 16:24 UTC, juanlopez4691 commented on src/WooCommerce.php
> +      // $price = apply_filters($current_filter, $price, $product);
🙈

2020-08-28 10:51 UTC, fabianmarz approved these changes

2020-08-31 07:34 UTC, merged