Removed trailing slashes in product filter to avoid unnecessary redirects.
netzstrategen/wordpress-shop-standards pull request #136
Opened 2021-03-11 17:10 UTC by Mauricio-Urrego

### Ticket
- [Product category filter: Attribute facet filter submits to a wrong URL causing redirect (adding 0.5s)](https://app.asana.com/0/30156186242982/1200027730245172/f)

### Description
-

2021-03-11 18:43 UTC, sun requested changes
We can't do this in shop-standards, because a shop does not necessarily have permalinks configured to omit trailing slashes.

However, GACO has permalinks configured without trailing slash, so the layered_nav_dropdown should produce the correct links already. Can you check whether they might get overridden by custom code or another plugin (Yoast?)?

2021-03-12 09:13 UTC, bogdanarizancu requested changes

2021-03-12 09:13 UTC, bogdanarizancu commented on src/ProductFilters/WidgetLayeredNav.php
> +    $output =  preg_replace("/gartenmoebel\//", "gartenmoebel", $output);;
```suggestion
    $output =  preg_replace("/gartenmoebel\//", "gartenmoebel", $output);
```

2021-03-12 12:27 UTC, Mauricio-Urrego commented on src/ProductFilters/WidgetLayeredNav.php
> +    $output =  preg_replace("/gartenmoebel\//", "gartenmoebel", $output);;
Oops

2021-03-12 12:29 UTC, Mauricio-Urrego commented
> We can't do this in shop-standards, because a shop does not necessarily have permalinks configured to omit trailing slashes.
> 
> However, GACO has permalinks configured without trailing slash, so the layered_nav_dropdown should produce the correct links already. Can you check whether they might get overridden by custom code or another plugin (Yoast?)?

We decided on a call to go with a different strategy here. Will try removing trailing slashes using home_url filter.

2021-03-12 15:46 UTC, Mauricio-Urrego commented
Went with this filter now as the strategy. Filter is being called in too late though. Needs further testing...

wp-content/plugins/custom/src/WooCommerce.php:
 ```
/**
   * Prevents unnecessary redirect due to '?/' for get parameters.
   *
   * @implements home_url
   */
  public static function home_url($url, $path, $orig_scheme, $blog_id) {
    if ($path && strpos($url, '/?') !== FALSE) {
      $url = str_replace('/?', '?', $url);
    }
    return $url;
  }
```
wp-content/plugins/custom/src/Plugin.php:
```
// Remove trailing slash form the filter form action.
add_filter('home_url', __NAMESPACE__ . '\WooCommerce::home_url', 1, 4);
```

2021-03-14 15:16 UTC, Mauricio-Urrego commented
This PR has been replaced with: https://github.com/netzstrategen/gaco/pull/621

2021-03-14 15:16 UTC, Mauricio-Urrego commented
This PR has been replaced with: https://github.com/netzstrategen/gaco/pull/621

2021-03-14 15:16 UTC, closed without merging