Removes the page 1 suffix from archive URLs.
netzstrategen/wordpress-shop-standards pull request #139
Opened 2021-05-12 12:06 UTC by Mauricio-Urrego

### Ticket
- [Prevent pagination links to page 1 that contain the page suffix. ](https://app.asana.com/0/507013885678070/1200321868255267/f)

### Description
-

2021-05-17 07:15 UTC, bogdanarizancu approved these changes

2021-05-25 09:46 UTC, sun requested changes

2021-05-25 09:46 UTC, sun commented on src/Plugin.php
> +     */
Only a inline comment (single line summary) here; PHPDoc block is only for the separate function definition.

2021-05-25 09:46 UTC, sun commented on src/Plugin.php
> +    });
Please move to a separate static function/callback.

2021-05-25 10:57 UTC, sun approved these changes
@Mauricio-Urrego I corrected the PR title. It should state the original problem that is being addressed by the proposed change.

Please squash-merge using the corrected PR title as commit message.

2021-05-25 10:57 UTC, sun commented on src/Plugin.php
> +    // Removes the `/page/1` suffix from archive URLs.
Avoid backticks in PHP code whenever possible, they are the shorthand operator for executing shell commands:
https://www.php.net/manual/en/language.operators.execution.php

```suggestion
    // Removes the suffix '/page/1' from archive URLs.
```

2021-05-25 10:57 UTC, sun commented on src/Plugin.php
> +   * Removes the `/page/1` suffix from archive URLs.
```suggestion
   * Removes the suffix '/page/1' from archive URLs.
```

2021-05-27 08:36 UTC, merged