Patches pagination in elementor product widget.
netzstrategen/wordpress-shop-standards pull request #140
Opened 2021-05-12 18:47 UTC by Mauricio-Urrego

### Ticket
- [Elementor: pagination clicks reload full page - no anchor](https://app.asana.com/0/30156186242982/1200264058586621/f)

### Description
-

2021-05-25 18:04 UTC, sun requested changes

2021-05-25 18:04 UTC, sun commented on assets/scripts/main.js
> +    $('.elementor-widget-woocommerce-products').attr('id', $('.elementor-widget-woocommerce-products').attr('data-id'));
```suggestion
    const $widget = $('.elementor-widget-woocommerce-products');
    if (!$widget.attr('id')) {
      $widget.attr('id', $widget.attr('data-id'));
    }
```
You can use the same `$widget` as context for the selector looking for all links below.

2021-05-25 18:04 UTC, sun commented on assets/scripts/main.js
> +      $(a).attr('href', $(a).attr('href') + '#' + $('.elementor-widget-woocommerce-products').attr('id'));
The first argument (which you named `i`) should contain the full jQuery object of the link already, no?

In addition, there may be multiple product listing widgets on a single page, so you should find the closest to the link:
```suggestion
      $(a).attr('href', $(a).attr('href') + '#' + $(a).closest('.elementor-widget-woocommerce-products').attr('id'));
```

2021-05-26 16:35 UTC, sun commented
@Mauricio-Urrego I tested and my last suggestions on this PR should work correctly. Please have another look.

![image](https://user-images.githubusercontent.com/41992/119698043-22c69480-be51-11eb-8a76-64cbf8f919c7.png)

2021-05-27 07:12 UTC, sun approved these changes

2021-05-27 07:12 UTC, sun commented
The code should work, seems like something else is conflicting.

2021-06-01 07:14 UTC, fabianmarz requested changes
Blocking for now as the compiled file is missing.

2021-06-01 09:55 UTC, fabianmarz commented
Just a quick heads up. This is not working because some other elementor function (`handleAnchorLinks`)[https://github.com/elementor/elementor/blob/2cd3d50d8d87edde9cd3c820f5a0f8b1f2c4f24f/assets/dev/js/frontend/utils/anchors.js#L64] code is hooking into all anchors and puts a `e.preventDefault` if it's an internal link 🤔 

I'm currently looking into a viable solution.

2021-06-01 11:49 UTC, Mauricio-Urrego commented
> Just a quick heads up. This is not working because some other elementor function (`handleAnchorLinks`)[https://github.com/elementor/elementor/blob/2cd3d50d8d87edde9cd3c820f5a0f8b1f2c4f24f/assets/dev/js/frontend/utils/anchors.js#L64] code is hooking into all anchors and puts a `e.preventDefault` if it's an internal link 🤔
> 
> @Mauricio-Urrego, could you please test my commit? I remove the click event listeners to prevent elementor from treating these links as anchor target links. I guess it's save to remove the click listeners all together as there should not be any attached.

Works for me! Just need to commit compiled assets then?

2021-06-01 13:01 UTC, fabianmarz approved these changes

2021-06-01 13:01 UTC, merged